GIFTS = (
    "Orange (fruit)",
    "Sandales",
    "Chocolats",
    "Peluche Pokemon",
    "Peluche Lilo & Stich",
    "Nougat",
    "Bonbons divers",
    "Coffret Blu-ray JoJo",
    "Costume de weeb",
    "Coffret DVD Game of Thrones",
    "Coffret DVD Buffy c/ les vampires",
    "Coffret DVD Charmed",
    "Coffret DVD Sous le soleil",
    "Kit pour faire soi-même des bières deg.",
    "Graines de tomate",
    "Abonnement Netflix",
    "Abonnement Amazon Prime",
    "Intégrale d'Elton John",
    "Vinyl Engelwood - Crystal Dolphin",
    "Discord Nitro",
    "Vinyl de shoegaze",
    "Paire de baskets",
    "Peluche collector \"Père singe\"",
    "Peluche collector \"Neron de Nöel\"",
    "Claquette oppressante",
    "Airpods",
    "iPhone 12",
    "PS5",
    "Xbox Series X",
    "Switch",
    "RTX 3080",
    "RX 6800 XT",
    "Billet pour Disneyland",
    "Porsche 911",
    "Voyage en Islande",
    "Pack Adobe",
    "Pendentif rare",
    "Lingot d'or",
    "Tous les DLC Europa Universalis IV",
    "EVA-01",
    "Porte des étoiles",
    "Actions chez Microsoft",
    "Actions chez Amazon",
    "Actions chez Google",
    "Cyberbug2077"
)

DESTINATIONS = (
    ("Pékin", "Chine"),
    ("Tokyo", "Japon"),
    ("Kinshasa", "République Démocratique du Congo"),
    ("Moscou", "Russie"),
    ("Séoul", "Corée du Sud"),
    ("Jakarta", "Indonésie"),
    ("Dacca", "Bangladesh"),
    ("Mexico", "Mexique"),
    ("Londres", "Royaume-Uni"),
    ("Lima", "Pérou"),
    ("Bangkok", "Thaïlande"),
    ("Téhéran", "Iran"),
    ("Bogota", "Colombie"),
    ("Le Caire", "Egypte"),
    ("Bagdad", "Iraq"),
    ("Singapour", "Singapour"),
    ("Ankara", "Turquie"),
    ("Santiago", "Chili"),
    ("Riyad", "Arabie Saoudite"),
    ("Alger", "Algérie"),
    ("Berlin", "Allemagne"),
    ("Damas", "Syrie"),
    ("Hanoï", "Viêt Nam"),
    ("Madrid", "Espagne"),
    ("Pyongyang", "Corée du Nord"),
    ("Kaboul", "Afghanistan"),
    ("Nairobi", "Kenya"),
    ("Addis-Abeba", "Ethiopie"),
    ("Buenos Aires", "Argentine"),
    ("Rome", "Italie"),
    ("Kiev", "Ukraine"),
    ("Taipei", "Taïwan"),
    ("Brasilia", "Brésil"),
    ("Amman", "Jordanie"),
    ("Luanda", "Angola"),
    ("Pretoria", "Afrique du Sud"),
    ("Paris", "France"),
    ("Tachkent", "Ouzbékistan"),
    ("Bakou", "Azerbaïjan"),
    ("Stockholm", "Suède"),
    ("La Havane", "Cuba"),
    ("Phnom Penh", "Cambodge"),
    ("Bucarest", "Roumanie"),
    ("Caracas", "Venezuela"),
    ("Rabat", "Maroc"),
    ("Vienne", "Autriche"),
    ("Khartoum", "Soudan"),
    ("Budapest", "Hongrie"),
    ("Varsovie", "Pologne"),
    ("Minsk", "Biélorussie"),
    ("Manille", "Philippines"),
    ("Kampala", "Ouganda"),
    ("Accra", "Ghana"),
    ("Yaoundé", "Cameroun"),
    ("Antananarivo", "Madagascar"),
    ("Beyrouth", "Liban"),
    ("Quito", "Equateur"),
    ("Harare", "Zimbabwe"),
    ("Ourlan-Bator", "Mongolie"),
    ("Doha", "Qatar"),
    ("Sanaa", "Yémen"),
    ("Conakry", "Guinée"),
    ("Kuala Lumpur", "Malaisie"),
    ("Montevideo", "Uruguay"),
    ("Lusaka", "Zambie"),
    ("Bamako", "Mali"),
    ("Prague", "République Tchèque"),
    ("Port-au-Prince", "Haïti"),
    ("Tripoli", "Libye"),
    ("Koweït", "Koweït"),
    ("Belgrade", "Serbie"),
    ("Saint-Domingue", "République dominicaine"),
    ("Mogadiscio", "Somalie"),
    ("Gitega", "Burundi"),
    ("Bruxelles", "Belgique"),
    ("Brazzaville", "Congo"),
    ("Erevan", "Arménie"),
    ("Maputo", "Mozambique"),
    ("Freetown", "Sierra Leone"),
    ("Tbilissi", "Géorgie"),
    ("Dakar", "Sénégal"),
    ("Ouagadougou", "Burkina Faso"),
    ("Dublin", "Irlande"),
    ("Monrovia", "Liberia"),
    ("Guatemala", "Guatemala"),
    ("Islamabad", "Pakistan"),
    ("Managua", "Nicaragua"),
    ("Naypyidaw", "Myanmar"),
    ("Lilongwe", "Malawi"),
    ("Jerusalem", "Israel"),
    ("Ottawa", "Canada"),
    ("Sucre", "Bolivie"),
    ("Bichkek", "Kirghizstan"),
    ("Noursoultan", "Kasakhstan"),
    ("Lomé", "Togo"),
    ("Panama", "Panama"),
    ("Katmandou", "Népal"),
    ("Amsterdam", "Pays-Bas"),
    ("Zagreb", "Croatie"),
    ("Mascate", "Oman"),
    ("Niamey", "Niger"),
    ("Chisinau", "Moldavie"),
    ("Abuja", "Nigeria"),
    ("Tirana", "Albanie"),
    ("Tunis", "Tunisie"),
    ("Achgabat", "Turkménistan"),
    ("N'Djaména", "Tchad"),
    ("Tegucigalpa", "Honduras"),
    ("Bangui", "République centrafricaine"),
    ("Athènes", "Grèce"),
    ("Nouakchott", "Mauritanie"),
    ("Kigali", "Rwanda"),
    ("Riga", "Lettonie"),
    ("Kingston", "Jamaique"),
    ("Washington (DC)", "Etats-Unis"),
    ("Oslo", "Norvège"),
    ("Helsinki", "Finlande"),
    ("Abou Dhabi", "Emirats Arabes Unis"),
    ("Douchanbé", "Tadjikistan"),
    ("Vilnius", "Lituanie"),
    ("Libreville", "Gabon"),
    ("Asmara", "Erythrée"),
    ("Lisbonne", "Portugal"),
    ("San Salvador", "El Salvador"),
    ("Asuncion", "Paraguay"),
    ("Skopje", "Macédoine"),
    ("Copenhage", "Danemark"),
    ("Djibouti", "Djibouti"),
    ("Yamoussoukro", "Côte d'Ivoire"),
    ("Bissau", "Guinée-Bissau"),
    ("Bratislava", "Slovaquie"),
    ("Tallinn", "Estonie"),
    ("Sofia", "Bulgarie"),
    ("Sarajevo", "Bosnie-Herzégovine"),
    ("Wellington", "Nouvelle-Zélande"),
    ("Djouba", "Sud-Soudan"),
    ("Canberra", "Australie"),
    ("San José", "Costa Rica"),
    ("Port Moresby", "Papouasie-Nouvelle-Guinée"),
    ("Vientiane", "Laos"),
    ("Dodoma", "Tanzanie"),
    ("Maseru", "Lesotho"),
    ("Nicosie", "Chypre"),
    ("Ljubljana", "Slovénie"),
    ("Paramaribo", "Suriname"),
    ("Windhoek", "Namibie"),
    ("New Delhi", "Inde"),
    ("Nassau", "Bahamas"),
    ("Gaborone", "Botswana"),
    ("Porto-Novo", "Bénin"),
    ("Pristina", "Kosovo"),
    ("Podgorica", "Monténégro"),
    ("Port-Louis", "Maurice"),
    ("Manama", "Bahreïn"),
    ("Berne", "Suisse"),
    ("Georgetown", "Guyana"),
    ("Praia", "Cap-Vert"),
    ("Sri Jayawardenapura Kotte", "Sri lanka"),
    ("Reykjavik", "Islande"),
    ("Bridgetown", "Barbade"),
    ("Malé", "Maldives"),
    ("Malabo", "Guinée équatoriale"),
    ("Thimpu", "Bhoutan"),
    ("Suva", "Fidji"),
    ("Mbabane", "Eswatini"),
    ("Luxembourg", "Luxembourg"),
    ("Castries", "Sainte-Lucie"),
    ("Moroni", "Comores"),
    ("Honiara", "Salomon"),
    ("Dili", "Timor-Oriental"),
    ("Sao Tome", "Sao Tomé-et-Principe"),
    ("Port d'Espagne", "Trinidad-et-Tobago"),
    ("Kingstown", "Saint-Vincent-et-les-Grenadines"),
    ("Apia", "Samoa"),
    ("Port Vila", "Vanuatu"),
    ("Monaco", "Monaco"),
    ("Banjul", "Gambie"),
    ("Tarawa", "Kiribati"),
    ("Victoria", "Seychelles"),
    ("Bandar Seri Begawan", "Brunei"),
    ("Delap-Uliga-Darrit", "Iles Marshall"),
    ("Andorre-la-Vieille", "Andorre"),
    ("Saint John's", "Antigua-et-Barbuda"),
    ("Nuku'alofa", "Tonga"),
    ("Belmopan", "Belize"),
    ("Roseau", "Dominique"),
    ("Basseterre", "Saint-Christophe-et-Niévès"),
    ("Palikir", "Micronésie"),
    ("Saint-Georges", "Grenade"),
    ("La Valette", "Malte"),
    ("Vaduz", "Liechtenstein"),
    ("Saint-marin", "Saint-Marin"),
    ("Funafuti", "Tuvalu"),
    ("Tifariti", "Sahara occidental"),
    ("Yaren", "Nauru"),
    ("Vatican", "Vatican"),
    ("Melekeok", "Palaos"),
    ("Nuuk", "Groenland"),
    ("Alofi", "Niue")
)

ASTUCES = (
    "Les cadeaux donnés en récompense de la résolution d'un problème de livraison sont forcément de niveau 3",
    "Les joueurs répondant correctement aux questions de capitales/pays ont 3x plus de points personnels que dans les autres cas",
    "Le bot marquera une pause dans le voyage si peu de gens parlent sur le serveur",
    "Louper une destination fait baisser le niveau des cadeaux qui auraient dû être livrés",
    "Si un cadeau niv. 1 n'est pas livré, il est définitivement perdu !",
    "Le leader n'a besoin d'aucune permission : il peut tout faire dans sa team !",
    "La permission de livraison est donnée par défaut lorsqu'un membre rejoint une team, mais on peut la lui retirer",
    "Le leader peut donner des permissions pour se décharger de certaines actions comme le recrutement de membres",
    "Utilisez \";team stock\" pour voir les prochaines livraisons à effectuer !"
)