PASSIFS = {
    "sore_loser" : {"name": "Mauvais perdant",
                    "desc": "Chance de tuer son assassin à sa mort"},
    "nurse": {"name": "Infirmier",
              "desc": "Régénération lente et constante de la vie"},
    "athletic": {"name": "Athlétique",
                 "desc": "Immunité contre les effets de la fatigue"},
    "guardian": {"name": "Gardien",
                 "desc": "Bonus de stats lorsque se trouve dans une équipe"},
    "traitor": {"name": "Traître",
                "desc": "Malus de stats pour les autres membres de son équipe une fois dissoute"},
    "zombie": {"name": "Zombie",
               "desc": "Réssucité avec 1 PV lors de la première mort (sauf coup critique)"},
    "serial_killer": {"name": "Tueur en série",
                      "desc": "Bonus de stats à chaque membre éliminé"},
    "stealthy": {"name": "Furtif",
                 "desc": "100% de chance de réussite lors de la fuite"},
    "mafia_boss": {"name": "Boss de la Mafia",
                   "desc": "Démarre la partie avec un item de sponsor aléatoire"},
    "thief": {"name": "Voleur",
              "desc": "Vole aléatoirement un item à un autre membre tous les 4 cycles"},
    "nox": {"name": "Nox",
            "desc": "Immunisé contre les malus de la nuit"}
}